pipelineId: initilized-pipeline
description: TODO - describe your pipeline
runner: 'airflow'
owner: 'data-eng-team'
modelVersion: 'v2'
defaults:
  projectId: {{ project }}
  location: {{ region }}
  executionConfig:
    retries: 1

triggers:
  - schedule:
      interval: '0 2 * * *'  # 2 AM daily
      startTime: '2025-11-01T00:00:00'
      endTime: '2026-12-01T00:00:00'
      catchup: false
      timezone: 'UTC'

# Add your jobs here
actions:
  - pyspark:
      name: fibonacci_serverless
      engine:
        dataprocServerless:
          resourceProfile:
            path: serverless-profile.yaml
      mainFilePath: fibonacci.py

  - pyspark:
      name: fibonacci_ephemeral
      engine:
        dataprocOnGce:
          ephemeralCluster:
            clusterName: fibonacci-ephemeral
            resourceProfile:
              path: ephemeral-profile.yaml
      mainFilePath: fibonacci.py